#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Users/dddddd/development/flutter"
export "FLUTTER_APPLICATION_PATH=/Users/dddddd/Documents/GitHub/flutter_inappwebview/example"
export "FLUTTER_TARGET=lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "SYMROOT=${SOURCE_ROOT}/../build/ios"
export "FLUTTER_BUILD_NAME=1.0.0"
export "FLUTTER_BUILD_NUMBER=1"
export "DART_DEFINES=Zmx1dHRlci5pbnNwZWN0b3Iuc3RydWN0dXJlZEVycm9ycz10cnVl,RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ=="
# export "OTHER_LDFLAGS=$(inherited) -framework Flutter"
# export "FLUTTER_FRAMEWORK_DIR=/Users/dddddd/development/flutter/bin/cache/artifacts/engine/ios"
# export "FLUTTER_BUILD_NAME=1.11.2"
# export "FLUTTER_BUILD_NUMBER=55"
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=false"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=/Users/lorenzopichilli/Desktop/flutter_inappwebview/example/.dart_tool/package_config.json"
